#!/usr/bin/env bash
set -o errexit

# N4IRS 06/15/2018

#################################################
#                                               #
#                                               #
#                                               #
#################################################

# USART1 - TXD PA9  - RXD PA10 (MMDVM-Pi board, MMDVM-Pi F722 board, MMDVM-F4M board, STM32F722-F7M board, STM32F4-DVM board)
# USART2 - TXD PA2  - RXD PA3  (Nucleo64 F446RE board, Morpho or Arduino header)
# USART3 - TXD PC10 - RXD PC11 (Discovery board)
# USART3 - TXD PD8  - RXD PD9  (Nucleo144 F767ZI board)

# - Serial repeater:
# USART1 - TXD PA9  - RXD PA10 (Nucleo with Arduino header)
# UART5  - TXD PC12 - RXD PD2 (Discovery, MMDVM-Pi, MMDVM-Pi F722 board, MMDVM-F4M board, STM32F722-F7M board, STM32F4-DVM board, Nucleo64 with Morpho header and Nucleo144 F767ZI)

make pi         # MMDVM-Pi board
make pi-f722    # MMDVM-Pi F722 board
make f4m        # MMDVM-F4M board
make f7m        # STM32F722-F7M board
make nucleo	# Nucleo64 F446RE board
make dis        # Discovery board
make f767	# Nucleo144 F767ZI board
make dvm        # STM32F4-DVM board



make clean
make pi		# MMDVM-Pi board
make clean
make pi-f722	# MMDVM-Pi F722 board
make clean
make f4m	# MMDVM-F4M board
make clean
make f7m	# STM32F722-F7M board
make clean
make nucleo
make clean
make dis	# Discovery board
make clean
make f767
make clean
make dvm	# STM32F4-DVM board
make clean
# release_f4

# release_f7

# clean

# deploy

# deploy-f7

# deploy-pi

# deploy-f4m

# deploy-dvm

# deploy-pi-f7

# deploy-f7m

