#!/usr/bin/env bash
# set -o errexit

# N4IRS 07/26/2017

#################################################
#                                               #
#                                               #
#                                               #
#################################################

systemctl stop nxdngateway.service
systemctl stop nxdnparrot.service
systemctl stop p25gateway.service
systemctl stop p25parrot.service
systemctl stop ysfgateway.service
systemctl stop ysfparrot.service
systemctl stop mmdvm_bridge.service
systemctl stop analog_bridge
systemctl stop quantar_bridge
systemctl stop md380-emu

